import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppbarClient } from "./components/AppbarClient";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" h-screen">
      <Providers>
        <body className={inter.className}>
          <div>
            <div className="fixed top-0 w-screen"><AppbarClient /></div>
            <div className="">
              {children}
            </div>
          </div>
        </body>
      </Providers>
    </html>
  );
}
